Tensors : Container of Data 
    0 Dimension Tensor

In [1]:
import numpy as np
x = np.array(12)

In [2]:
x

array(12)

In [3]:
x.ndim 

0

1 Dimensional Tensors

In [4]:
x = np.array([12,3,6,14])
x

array([12,  3,  6, 14])

In [5]:
x.ndim

1

2 D Tensors
2 Axes : rows and columns

In [6]:
x = np.array([
              [5,7,1,2,7],
              [6,5,2,5,1],
              [7,9,1,5,2]
             ])

In [7]:
x

array([[5, 7, 1, 2, 7],
       [6, 5, 2, 5, 1],
       [7, 9, 1, 5, 2]])

In [8]:
x.ndim

2

3 D Tensor

In [9]:
x = np.array([[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]]])

In [10]:
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [11]:
print("Helo")

Helo
