<a href="https://colab.research.google.com/github/klnsuman/DeepLearning/blob/master/TF_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
#import tensorflow.examples.tutorials.mnist.input_data as input_data
import tensorflow_datasets as tfds


dataset = tfds.load(name="mnist", split=tfds.Split.TRAIN)

local data directory. If you'd instead prefer to read directly from our public
GCS bucket (recommended if you're running on GCP), you can instead pass
`try_gcs=True` to `tfds.load` or set `data_dir=gs://tfds-data/datasets`.





Dataset mnist downloaded and prepared to /root/tensorflow_datasets/mnist/3.0.1. Subsequent calls will reuse this data.


In [2]:
print(dataset)

<PrefetchDataset shapes: {image: (28, 28, 1), label: ()}, types: {image: tf.uint8, label: tf.int64}>


In [6]:

!pip install watermark

In [7]:
%load_ext watermark
%watermark -a 'Suman' -v -p tensorflow

Suman 

CPython 3.6.9
IPython 5.5.0

tensorflow 2.4.1


In [60]:
mnist = tf.keras.datasets.mnist

In [61]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [62]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [63]:
x_train.shape,y_train.shape

((60000, 28, 28), (60000,))

In [47]:
import numpy as np
np.unique(y_train)

array([0.        , 0.00392157, 0.00784314, 0.01176471, 0.01568627,
       0.01960784, 0.02352941, 0.02745098, 0.03137255, 0.03529412])

In [64]:
model = tf.keras.models.Sequential([
      tf.keras.layers.Flatten(input_shape=(28,28)),
      tf.keras.layers.Dense(128,activation='relu'),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(10)
])

In [65]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.19947225,  0.9448664 , -0.8153819 ,  0.00287242, -0.5382146 ,
         0.22450075,  0.4373153 , -0.6347611 ,  0.15198919, -0.01600382]],
      dtype=float32)

In [66]:
tf.nn.softmax(predictions).numpy()

array([[0.07515709, 0.2360206 , 0.04059605, 0.09201255, 0.0535619 ,
        0.11484156, 0.14207684, 0.04863248, 0.10680897, 0.09029199]],
      dtype=float32)

In [68]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [70]:
loss_fn(y_train[:1], predictions).numpy()

2.1642017

In [71]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [72]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4817 - accuracy: 0.8585
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1552 - accuracy: 0.9549
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1090 - accuracy: 0.9683
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0868 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0745 - accuracy: 0.9779


In [73]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0752 - accuracy: 0.9775


[0.07522382587194443, 0.9775000214576721]

In [74]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [75]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.84059433e-07, 9.38007361e-09, 2.83335721e-05, 8.06949392e-04,
        1.74837034e-10, 1.30081480e-06, 3.12642409e-13, 9.99145865e-01,
        1.60925561e-06, 1.54987392e-05],
       [1.62223512e-09, 5.85617381e-04, 9.99404073e-01, 4.59911689e-06,
        5.51203514e-17, 5.33069533e-06, 8.46637871e-09, 6.90660026e-14,
        3.87625732e-07, 1.16058370e-11],
       [3.98318548e-07, 9.98169303e-01, 1.00481571e-04, 4.72686297e-05,
        1.21966528e-04, 1.20828830e-04, 2.01092535e-05, 4.92380408e-04,
        9.16256860e-04, 1.10884312e-05],
       [9.99548256e-01, 1.28315385e-08, 2.37410684e-04, 5.67688403e-08,
        9.18426451e-07, 9.95761002e-06, 3.41535197e-05, 1.41318800e-04,
        2.29900877e-07, 2.76709488e-05],
       [8.87293481e-07, 1.60386104e-08, 1.56147041e-06, 2.87724440e-08,
        9.98648584e-01, 9.11951474e-08, 1.31475133e-07, 5.42244779e-05,
        1.78956128e-07, 1.29433174e-03]], dtype=float32)>